Propose erlang reusable workflow
valitydev/erlang-workflows pull request #1
Opened 2022-01-21 16:36 UTC by kehitt

Мне кажется, что в reusable workflow можно (и нужно) отказаться от внешней конфигурации make, которая, по сути, наполовину определяет работу пайплайна CI. Это позволит, как минимум, не заморачиваться возможными различиями/ошибочными изменениями от репозитория к репозиторию.

Само право на существование makefile со всеми wc-/wdeps- фичами это, конечно, не затрагивает, но кмк это больше уровень QoL разработчика.

2022-01-22 07:19 UTC, ndiezel0 commented
Не согласен, по моему мнению работа через Makefile позволяет нам репродуцировать работу CI на локальной машине, что очень помогает в отладке. К тому же CI через workflow проверяет работу на раннере, который к образу никакого отношения не имеет, а не в финальном образе, который и будет задеплоен. Грубо говоря: мы можем не положить в образ нужную зависимость и не заметить это на CI.

2022-01-22 11:20 UTC, kehitt commented
> Не согласен, по моему мнению работа через Makefile позволяет нам репродуцировать работу CI на локальной машине, что очень помогает в отладке. 

Нет, тут я конечно согласен, удобно.

Основной моей идеей тут было то, что раз у нас появляется organisation-wide workflow, не плохо бы заставить его автоматически енфорсить какие-то organisation-wide политики, к примеру - "организация требует запускать dialyze в тестовом профиле", "организация требует предоставлять статистику по coverage", и тому подобные. Тогда получится, что вместо того чтобы постоянно проверять эти вещи от репозитория к репозиторию (от PR к PR), можно будет просто проверять что мы используем этот reusable workflow и потому имеем какие-то гарантии. 

Long story short, мне не очень нравится, что в Makefile можно написать `exit 0` и получить зеленую галочку на PR, особенно в контексте того что мы успешный опенсурс и у нас тысячи PRов от третьих лиц в неделю. 🌝

Я не спорю, что этот подход больше не будет обеспечивать полное соответсвие окружений Makefile и CI, что может быть не удобно. Основные параметры этих окружений, вроде версии OTP, все еще можно будет синхорнизировать через .env, но обеспечить соответсвие уровней ниже, конечно, будет сложнее (хотя получается, что если ты сидишь на M1, то его все равно не будет, даже через Makefile). Плюс пока не очень понятно как заносить, например, генерацию swag (через rebar pre_hook?).

В общем, мне интересно ваше мнение по поводу целесообразности этой затеи в целом. Конкретную реализацию можно допилить в процессе, но если в этом обсуждении мы установим, что мои беспокойства напрасны, то конечно нету смысла 🥐

> К тому же CI через workflow проверяет работу на раннере, который к образу никакого отношения не имеет, а не в финальном образе, который и будет задеплоен. Грубо говоря: мы можем не положить в образ нужную зависимость и не заметить это на CI.

Но ведь и Makefile проверяет работу не в образе, который будет задеплоен (Dockerfile), а в девелоперском (Dockerfile.dev). Мне кажется что такую проблему лучше решить внесением изменений в воркфлоу, который делает, собсвтенно, релизы, чтобы он каким то образом пытался запустить то, что он только что собрал, хотя бы до уровня базового хелсчека.

2022-01-24 09:39 UTC, kehitt commented
По просьбе @keynslug, примерно то, как подключать:

- Файл `.env`:
```
OTP_VERSION=24.2.0
REBAR_VERSION=3.18
THRIFT_VERSION=0.14.2.1
```

- Файл `.github/workflows/ci.yml`:

```yaml

name: Erlang Service CI

on:
  push:
    branches:
      - 'master'
      - 'epic/**'
  pull_request:
    branches: [ '**' ]

jobs:
  setup:
    name: Load .env
    runs-on: ubuntu-latest
    outputs:
      otp-version: ${{ steps.otp-version.outputs.version }}
      rebar-version: ${{ steps.rebar-version.outputs.version }}
      thrift-version: ${{ steps.thrift-version.outputs.version }}
    steps:
      - run: grep -v '^#' .env >> $GITHUB_ENV
      - id: otp-version
        run: echo "::set-output name=version::$OTP_VERSION"
      - id: rebar-version
        run: echo "::set-output name=version::$REBAR_VERSION"
      - id: thrift-version
        run: echo "::set-output name=version::$THRIFT_VERSION"

  run:
    needs: setup
    uses: valitydev/erlang-workflows/.github/workflows/erlang-parallel-build.yml@acbc73d39b4dd630d9c797ddaeb8af92fb071014
    with:
      otp-version: ${{ needs.setup.outputs.otp-version }}
      rebar-version: ${{ needs.setup.outputs.rebar-version }}
      thrift-version: ${{ needs.setup.outputs.thrift-version }}

```

Все остальные Dockerfile/Makefile/docker-compose.yml взять [отсюда](https://github.com/valitydev/dominant/pull/3) и перенести в `valitydev/erlang_templates`.

2022-01-24 09:54 UTC, keynslug commented
> Само право на существование makefile со всеми wc-/wdeps- фичами это, конечно, не затрагивает, но кмк это больше уровень QoL разработчика.

Я это если честно так же вижу. Отсюда собственно корни этих файлов `.env` и растут.

В моём представлении нам надо как-то добиться удачного компромисса между (потенциальной) воспроизводимостью CI активностей и продуктивностью разработчика. И в этом смысле непонятно, что бы мы выиграли, если бы CI активности в контейнере гоняли: по моей оценке в воспроизводимости мы бы особо не выиграли (потому что идеальной не добиться из-за различий сред исполнения), а в продуктивности − потеряли (потому что в CI становится замешан make, сборка контейнеров, и он работает медленнее).

> Грубо говоря: мы можем не положить в образ нужную зависимость и не заметить это на CI.

Поддерживаю @kehitt, это же всё равно не достигается тем, что ты `make wc-xref` дёрнешь на CI вместо `rebar3 xref`. А тем, что ты собранный образ запускаешь с конфигом из репозитория и проверяешь его жизнеспособность.

2022-01-25 16:05 UTC, ndiezel0 requested changes

2022-01-25 16:05 UTC, ndiezel0 commented on .github/workflows/erlang-parallel-build.yml
> +          thrift-version: ${{ inputs.thrift-version }}
Либо надо ставить этот step везде где может быть компилация, либо надо все таки кэшировать весть проект.

2022-01-26 15:33 UTC, ndiezel0 commented on .github/workflows/erlang-parallel-build.yml
> +          path: _build/*/lib
plugins тоже можно сразу кэшировать.

2022-01-26 15:33 UTC, ndiezel0 commented on .github/workflows/erlang-parallel-build.yml
> +          path: _build/*/lib
Быстрее будет качать кокретный профиль.
```suggestion
          path: _build/test/lib
```

2022-01-26 15:33 UTC, ndiezel0 commented on .github/workflows/erlang-parallel-build.yml
> +          path: _build/*/lib
```suggestion
          path: _build/default/lib
```

2022-01-26 15:33 UTC, ndiezel0 commented on .github/workflows/erlang-parallel-build.yml
> +          [[ "${{ inputs.service-name }}" == "" ]] && exit 1
Может тогда на него и полагаться, а не на значение `inputs.run-ct-with-compose`?

2022-01-26 15:33 UTC, ndiezel0 commented on .github/workflows/erlang-parallel-build.yml
> +        if: ${{ failure() && (steps.run-ct.outcome == 'failure' || steps.run-ct-w-compose.outcome == 'failure') }}
Избыточно.
```suggestion
        if: ${{ steps.run-ct.outcome == 'failure' || steps.run-ct-w-compose.outcome == 'failure' }}
```

2022-01-26 15:35 UTC, kehitt commented on .github/workflows/erlang-parallel-build.yml
> +        if: ${{ failure() && (steps.run-ct.outcome == 'failure' || steps.run-ct-w-compose.outcome == 'failure') }}
Проверял, не работает

2022-01-26 15:36 UTC, kehitt commented on .github/workflows/erlang-parallel-build.yml
> +          [[ "${{ inputs.service-name }}" == "" ]] && exit 1
Как-то не очень очевидно будет, лучше тогда `service-name` сделаю required.

2022-01-26 15:37 UTC, kehitt commented on .github/workflows/erlang-parallel-build.yml
> +          path: _build/*/lib
https://github.com/valitydev/woody_erlang/pull/1#discussion_r787093313 👀

2022-01-26 15:38 UTC, ndiezel0 commented on .github/workflows/erlang-parallel-build.yml
> +          [[ "${{ inputs.service-name }}" == "" ]] && exit 1
Ну если правильно назвать, то должно быть очевидно) `compose-service-name` и описание, что делает.

2022-01-26 15:41 UTC, ndiezel0 commented on .github/workflows/erlang-parallel-build.yml
> +          path: _build/*/lib
Хм, да кажется тоже встречалось. Тогда вопрос снят)

2022-01-26 15:51 UTC, ndiezel0 commented on .github/workflows/erlang-parallel-build.yml
> +        if: ${{ failure() && (steps.run-ct.outcome == 'failure' || steps.run-ct-w-compose.outcome == 'failure') }}
Да, судя по доке тут какое-то неявное поведение требующее явного вызова `jobs.status`. Хотели видимо всем жизнь облегчить)
https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions

2022-01-26 16:00 UTC, kehitt commented on .github/workflows/erlang-parallel-build.yml
> +          path: _build/*/lib
Судя по сорсцам actions/cache кеш все равно хранится в одном архиве, так что врядли тут будет разница. Я потестирую

2022-01-27 09:16 UTC, kehitt commented on .github/workflows/erlang-parallel-build.yml
> +          path: _build/*/lib
Эксперементальным путем установил, что test профиль все же зависит от default (хотя я тоже раньше почему то считал, что они самодостататочны), и отсутсвие default [вызывает рекомпиляцию](https://github.com/valitydev/token-keeper/runs/4963834857?check_suite_focus=true).

2022-01-27 10:28 UTC, keynslug commented on .github/workflows/erlang-parallel-build.yml
> +          docker-compose run --use-aliases --rm ${{ inputs.service-name }} rebar3 ct --cover
Пока такое предложение смог сформулировать.

Вводим конвенцию, что `run-ct-compose-container-name` по умолчанию `testrunner` или что-то вроде того, и стараемся этой конвенции везде следовать.

```suggestion
          docker-compose run --use-aliases --rm ${{ inputs.run-ct-compose-container-name }} rebar3 ct --cover
```

Соответственно, в `docker-compose.yml` этот контейнер тоже называем всегда `testrunner`. На том же уровне возможно понадобиться (ну либо по вкусу) добавить `hostname` / `aliases` для этого контейнера.

Что скажете?

2022-01-27 10:29 UTC, keynslug commented on .github/workflows/erlang-parallel-build.yml
> +          docker-compose run --use-aliases --rm ${{ inputs.service-name }} rebar3 ct --cover
Заодно избавляемся от постыдного коммента про `Keep in sync with ...`.

2022-01-27 11:38 UTC, kehitt commented on .github/workflows/erlang-parallel-build.yml
> +          docker-compose run --use-aliases --rm ${{ inputs.service-name }} rebar3 ct --cover
Тоже посещала какая-то такая мысль, думаю норм

2022-01-27 14:18 UTC, keynslug approved these changes

2022-01-28 14:17 UTC, keynslug commented
Го мержить и тэгать? 💣

2022-01-28 14:23 UTC, merged